name = "MIMEs"
uuid = "6c6e2e6c-3030-632d-7369-2d6c69616d65"
license = "MIT"
authors = ["Fons van der Plas <fons@plutojl.org>", "Takafumi Arakaki <aka.tkf@gmail.com>", "Thibaut Lienart <tlienart@me.com>"]
version = "0.1.1"

[compat]
julia = "1.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
